### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by SharkWipf** [qimaqi/Continuous-Pose-in-NeRF#2]
First of all, nice work on this project, I'm looking forward to the Nerfstudio example.

However, currently the code has no license.
This means it cannot actually be used by any other projects (neither open source nor commercial).
If this is intentional, it would be nice to clarify this.
If it isn't intentional, it would be necessary to add a LICENSE.md file (Github can help you with this).
If you're unsure on what license would be suitable, most freely usable projects in this field, including Nerfstudio, are using the Apache2 license, which would ensure the highest cross-project compatibility.

**Comment by qimaqi** [comment]
Oh thanks a lot for pointing this out! I will add liscence soon

**Comment by SharkWipf** [comment]
Thanks a lot! 🙏
Again, nice work on the project, I'm looking forward to the future.
